[package]
name = "ggez_pong"
version = "0.1.0"
authors = ["Ana ClaÌudia Lira Correia <anaclira.correia@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5.1"
# nalgebra = "0.19.0"
rand = "0.7.2"